# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  find_tag:
    runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - shell: bash
        run: |
          date +"%Y-%m-%dT%H:%S" > date.txt
          
      - name: Upload date for using in sub jobs
        uses: actions/upload-artifact@v2
        with:
          name: date
          path: date.txt
          
          
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    needs: find_tag
    steps:
      - name: Get date info
        uses: actions/download-artifact@v2
        with:
          name: date
      - shell: bash
        id: build_info
        run: |
          value=`cat date.txt`
          echo "Date is $value"
          echo "::set-output name=TAG::$value"
          
      - name: Print date
        run: echo ${{ steps.build_info.outputs.TAG }}
